esphome:
  name: covercast
  friendly_name: CoverCast
  min_version: 2025.10.5
  name_add_mac_suffix: false

esp32:
  variant: esp32
  framework:
    type: esp-idf

button:
  - platform: template
    name: "CoverCast Play-Pause"
    id: play_pause